Repository material-components/material-components-web, pull requests merged in 2020-08, with the labels that each got.

#6279 docs(segmented-button): Add README.md
  packages/mdc-segmented-button/README.md
Labels: cla: yes

#6343 fix(segmented-button): Use empty clientRect in default adapter
  packages/mdc-segmented-button/segment/foundation.ts
Labels: cla: yes

#6345 build: Exit with error when running unit test on forked repos
  .github/workflows/test.yml
Labels: cla: yes

#6350 docs(textfield): fix class name
  packages/mdc-textfield/character-counter/README.md
Labels: Ready for Google, cla: yes

#6353 build: skip executing unit tests on forked repos
  .github/workflows/test.yml
Labels: cla: yes

#6371 test: update to latest sass dependency
  package-lock.json
  package.json
  scripts/webpack/css-bundle-factory.js
  testing/featuretargeting/sass-test-compile.helper.ts
Labels: cla: yes

#6382 docs(segmented-button): Add README.md
  packages/mdc-segmented-button/README.md
Labels: cla: yes

#6380 fix(segmented-button): Move include statements to avoid nested classes
  packages/mdc-segmented-button/segment/_segment.scss
Labels: cla: yes

#6390 fix(data-table): Check if data table has checkboxes on destroy
  packages/mdc-data-table/component.ts
  packages/mdc-data-table/test/component.test.ts
Labels: Ready for Google, cla: yes

#6381 feat(segmented-button): Add select validations for singleSelect
  packages/mdc-segmented-button/segmented-button/component.ts
Labels: cla: yes

#6426 [docs] Pointed directly to the document with the list of component libraries
  docs/integrating-into-frameworks.md
Labels: cla: yes, needs-response
