Repository material-components/material-components-web, pull requests merged in 2020-01, with the labels that each got.

#5392 test(tab-bar): Remove screenshot tests for Tabs
  test/screenshot/golden.json
  test/screenshot/spec/mdc-tab-bar/classes/baseline.html
  test/screenshot/spec/mdc-tab-bar/fixture.js
  test/screenshot/spec/mdc-tab-bar/fixture.scss
  test/screenshot/spec/mdc-tab-bar/mixins/density.html
Labels: cla: yes

#5391 test(radio): Remove screenshot tests for Radio
  test/screenshot/golden.json
  test/screenshot/spec/mdc-radio/classes/baseline-touch-target.html
  test/screenshot/spec/mdc-radio/classes/baseline.html
  test/screenshot/spec/mdc-radio/fixture.js
  test/screenshot/spec/mdc-radio/fixture.scss
  test/screenshot/spec/mdc-radio/mixins/density.html
  test/screenshot/spec/mdc-radio/mixins/mixins.html
Labels: cla: yes

#5394 test(tabbar): Add Jasmine component test.
  packages/mdc-tab-bar/test/component.test.ts
  test/unit/mdc-tab-bar/mdc-tab-bar.test.js
  testing/dom/events.ts
Labels: cla: yes

#5395 chore: Add copybara comment lines for transforms
  packages/mdc-button/_mixins.scss
  packages/mdc-card/_mixins.scss
  packages/mdc-checkbox/_mixins.scss
  packages/mdc-chips/_mixins.scss
  packages/mdc-dialog/_mixins.scss
  packages/mdc-fab/_mixins.scss
  packages/mdc-icon-button/_mixins.scss
  packages/mdc-list/_mixins.scss
  packages/mdc-menu/_mixins.scss
  packages/mdc-radio/_mixins.scss
  packages/mdc-switch/_mixins.scss
  packages/mdc-tab/_mixins.scss
Labels: cla: yes

#5396 test(tabscroller): Add Jasmine foundation test.
  karma.conf.js
  packages/mdc-tab-scroller/test/foundation.test.ts
  test/unit/mdc-tab-scroller/foundation.test.js
Labels: cla: yes

#5393 test(tabbar): Remove Mocha foundation test.
  test/unit/mdc-tab-bar/foundation.test.js
Labels: cla: yes

#5399 test(tabscroller): Add Jasmine tests for scrollers, util files.
  packages/mdc-tab-scroller/test/rtl-default-scroller.test.ts
  packages/mdc-tab-scroller/test/rtl-negative-scroller.test.ts
  packages/mdc-tab-scroller/test/rtl-reverse-scroller.test.ts
  packages/mdc-tab-scroller/test/util.test.ts
  test/unit/mdc-tab-scroller/rtl-default-scroller.test.js
  test/unit/mdc-tab-scroller/rtl-negative-scroller.test.js
  test/unit/mdc-tab-scroller/rtl-reverse-scroller.test.js
  testing/dom/events.ts
Labels: cla: yes

#5403 test(tabscroller): Add Jasmine component test.
  packages/mdc-tab-scroller/test/component.test.ts
  test/unit/mdc-tab-scroller/mdc-tab-scroller.test.js
Labels: cla: yes

#5404 fix(checkbox): Replace unique-id with custom color hash function to generate keyframes
  packages/mdc-checkbox/_mixins.scss
  packages/mdc-theme/_functions.scss
Labels: cla: yes

#5405 docs: update button markup for getting started guide
  docs/getting-started.md
Labels: cla: yes, docs

#5356 feat(textfield): add end-alignment
  packages/mdc-textfield/README.md
  packages/mdc-textfield/_mixins.scss
  packages/mdc-textfield/mdc-text-field.scss
  test/screenshot/diffing.json
  test/screenshot/golden.json
  test/screenshot/spec/mdc-textfield/classes/baseline-end-aligned.html
  test/screenshot/spec/mdc-textfield/classes/textarea-end-aligned.html
  test/screenshot/spec/mdc-top-app-bar/classes/baseline-short-collapsed-with-action-items.html
Labels: Ready for Google, cla: yes

#5411 test(textfield): Convert foundation tests for character-counter to Jasmine
  karma.conf.js
  packages/mdc-textfield/character-counter/test/foundation.test.ts
  test/unit/mdc-textfield/mdc-text-field-character-counter-foundation.test.js
Labels: cla: yes

#5406 test(list): Add Jasmine foundation test.
  karma.conf.js
  packages/mdc-list/test/foundation.test.ts
  packages/mdc-tab-scroller/test/foundation.test.ts
  test/unit/mdc-list/foundation.test.js
Labels: cla: yes

#5410 test(menu): Add Jasmine foundation test.
  karma.conf.js
  packages/mdc-menu/test/foundation.test.ts
  test/unit/mdc-menu/menu.foundation.test.js
Labels: cla: yes

#5412 test(textfield): Convert foundation tests for helper-text to Jasmine
  packages/mdc-textfield/helper-text/test/foundation.test.ts
  test/unit/mdc-textfield/mdc-text-field-helper-text-foundation.test.js
Labels: cla: yes

#5413 test(textfield): Convert foundation tests for textfield icon to Jasmine
  packages/mdc-textfield/icon/test/foundation.test.ts
  test/unit/mdc-textfield/mdc-text-field-icon-foundation.test.js
Labels: cla: yes

#5409 test(chips): Delete screenshot tests
  test/screenshot/golden.json
  test/screenshot/spec/mdc-chips/classes/action.html
  test/screenshot/spec/mdc-chips/classes/choice.html
  test/screenshot/spec/mdc-chips/classes/filter.html
  test/screenshot/spec/mdc-chips/classes/input.html
  test/screenshot/spec/mdc-chips/fixture.js
  test/screenshot/spec/mdc-chips/fixture.scss
  test/screenshot/spec/mdc-chips/mixins/chip-set-spacing.html
  test/screenshot/spec/mdc-chips/mixins/density.html
  test/screenshot/spec/mdc-chips/mixins/fill-color-accessible.html
  test/screenshot/spec/mdc-chips/mixins/fill-color.html
  test/screenshot/spec/mdc-chips/mixins/height.html
  test/screenshot/spec/mdc-chips/mixins/horizontal-padding.html
  test/screenshot/spec/mdc-chips/mixins/ink-color.html
  test/screenshot/spec/mdc-chips/mixins/leading-icon-color.html
  test/screenshot/spec/mdc-chips/mixins/leading-icon-margin.html
  test/screenshot/spec/mdc-chips/mixins/leading-icon-size.html
  test/screenshot/spec/mdc-chips/mixins/outline.html
  test/screenshot/spec/mdc-chips/mixins/selected-ink-color.html
  test/screenshot/spec/mdc-chips/mixins/shape-radius.html
  test/screenshot/spec/mdc-chips/mixins/trailing-icon-color.html
  test/screenshot/spec/mdc-chips/mixins/trailing-icon-margin.html
  test/screenshot/spec/mdc-chips/mixins/trailing-icon-size.html
Labels: cla: yes

#5414 test(list): Add Jasmine component test.
  packages/mdc-list/test/component.test.ts
  test/unit/mdc-list/mdc-list.test.js
Labels: cla: yes

#5417 test(menu): Add Jasmine component test.
  packages/mdc-menu/test/component.test.ts
  test/unit/mdc-menu/mdc-menu.test.js
  testing/dom/events.ts
  testing/helpers/foundation.ts
Labels: cla: yes

#5418 test(textfield): Convert foundation unit tests for overall component to jasmine
  packages/mdc-textfield/test/foundation.test.ts
  test/unit/mdc-textfield/foundation.test.js
Labels: cla: yes

#5397 test(button): Remove screenshot tests of Button
  test/screenshot/golden.json
  test/screenshot/spec/mdc-button/classes/baseline-button-with-icons.html
  test/screenshot/spec/mdc-button/classes/baseline-button-with-trailing-icons.html
  test/screenshot/spec/mdc-button/classes/baseline-button-without-icons.html
  test/screenshot/spec/mdc-button/classes/baseline-link-with-icons.html
  test/screenshot/spec/mdc-button/classes/baseline-link-without-icons.html
  test/screenshot/spec/mdc-button/fixture.js
  test/screenshot/spec/mdc-button/fixture.scss
  test/screenshot/spec/mdc-button/mixins/container-fill-color.html
  test/screenshot/spec/mdc-button/mixins/density.html
  test/screenshot/spec/mdc-button/mixins/filled-accessible.html
  test/screenshot/spec/mdc-button/mixins/horizontal-padding-baseline.html
  test/screenshot/spec/mdc-button/mixins/icon-color.html
  test/screenshot/spec/mdc-button/mixins/ink-color.html
  test/screenshot/spec/mdc-button/mixins/shape-radius.html
  test/screenshot/spec/mdc-button/mixins/stroke-color.html
  test/screenshot/spec/mdc-button/mixins/stroke-width.html
Labels: cla: yes

#5421 test(textfield): Migrate component unit test for character counter to Jasmine
  packages/mdc-textfield/character-counter/test/component.test.ts
Labels: cla: yes

#5420 test(textfield): Add component unit tests for helper text
  packages/mdc-textfield/helper-text/test/component.test.ts
  test/unit/mdc-textfield/mdc-text-field-helper-text.test.js
Labels: cla: yes

#5422 test(infra): Use createMockFoundation helper.
  packages/mdc-checkbox/test/component.test.ts
  packages/mdc-chips/chip-set/test/component.test.ts
  packages/mdc-chips/chip/test/component.test.ts
  packages/mdc-list/test/component.test.ts
  packages/mdc-tab-bar/test/component.test.ts
  packages/mdc-tab-scroller/test/component.test.ts
  packages/mdc-tab/test/component.test.ts
Labels: cla: yes

#5425 test(data-table): Add data table foundation jasmine test
  karma.conf.js
  packages/mdc-data-table/test/foundation.test.ts
  test/unit/mdc-data-table/foundation.test.js
Labels: cla: yes

#5427 test(menusurface): Add Jasmine foundation test.
  karma.conf.js
  packages/mdc-menu-surface/test/foundation.test.ts
  test/unit/mdc-menu-surface/menu-surface.foundation.test.js
Labels: cla: yes

#5429 test(menusurface): Add Jasmine util test.
  packages/mdc-menu-surface/test/util.test.ts
  test/unit/mdc-menu-surface/util.test.js
Labels: cla: yes

#5424 test(textfield): Convert component unit tests for textfield to jasmine
  packages/mdc-textfield/test/component.test.ts
  test/unit/mdc-textfield/mdc-text-field.test.js
Labels: cla: yes

#5426 test(data-table): Add data table component Jasmine test.
  packages/mdc-data-table/test/component.test.ts
  test/unit/mdc-data-table/mdc-data-table.test.js
  testing/dom/index.ts
Labels: cla: yes

#5430 test(notched-outline): Add Jasmine foundation test
  karma.conf.js
  packages/mdc-notched-outline/test/foundation.test.ts
  test/unit/mdc-notched-outline/foundation.test.js
Labels: cla: yes

#5367 fix(textfield): add separate classes for leading/trailing icons
  packages/mdc-textfield/_mixins.scss
  packages/mdc-textfield/component.ts
  packages/mdc-textfield/constants.ts
  packages/mdc-textfield/icon/README.md
  packages/mdc-textfield/icon/_mixins.scss
  packages/mdc-textfield/icon/mdc-text-field-icon.scss
  packages/mdc-textfield/icon/test/foundation.test.ts
  packages/mdc-textfield/mdc-text-field.scss
  packages/mdc-textfield/test/component.test.ts
  test/screenshot/spec/mdc-textfield/classes/baseline-leading-icon.html
  test/screenshot/spec/mdc-textfield/classes/baseline-leading-trailing-icons.html
  test/screenshot/spec/mdc-textfield/classes/baseline-trailing-icon.html
  test/screenshot/spec/mdc-textfield/classes/baseline-without-label-with-icon.html
  test/screenshot/spec/mdc-textfield/classes/disabled-leading-icon.html
  test/screenshot/spec/mdc-textfield/classes/disabled-leading-trailing-icons.html
  test/screenshot/spec/mdc-textfield/classes/disabled-trailing-icon.html
  test/screenshot/spec/mdc-textfield/classes/focused-leading-icon.html
  test/screenshot/spec/mdc-textfield/classes/focused-leading-trailing-icons.html
  test/screenshot/spec/mdc-textfield/classes/focused-trailing-icon.html
  test/screenshot/spec/mdc-textfield/classes/invalid-focused-leading-icon.html
  test/screenshot/spec/mdc-textfield/classes/invalid-focused-leading-trailing-icons.html
  test/screenshot/spec/mdc-textfield/classes/invalid-focused-trailing-icon.html
  test/screenshot/spec/mdc-textfield/classes/invalid-leading-icon.html
  test/screenshot/spec/mdc-textfield/classes/invalid-leading-trailing-icons.html
  test/screenshot/spec/mdc-textfield/classes/invalid-trailing-icon.html
  test/screenshot/spec/mdc-textfield/mixins/density-leading-icon-invalid.html
  test/screenshot/spec/mdc-textfield/mixins/density-leading-icon.html
  test/screenshot/spec/mdc-textfield/mixins/disabled-1.html
  test/unit/mdc-textfield/mdc-text-field-icon.test.js
Labels: Ready for Google, cla: yes

#5423 test(textfield): Migrate component unit test for icon to Jasmine
  packages/mdc-textfield/component.ts
  packages/mdc-textfield/icon/test/component.test.ts
  packages/mdc-textfield/icon/test/foundation.test.ts
  test/unit/mdc-textfield/mdc-text-field-icon.test.js
Labels: cla: yes

#5432 test(line-ripple): Add Jasmine foundation unit tests
  karma.conf.js
  packages/mdc-line-ripple/test/foundation.test.ts
  test/unit/mdc-line-ripple/mdc-line-ripple-foundation.test.js
Labels: cla: yes

#5433 test(data-table): Remove screenshot tests for data table component
  test/screenshot/golden.json
  test/screenshot/spec/mdc-data-table/classes/baseline-checkbox.html
  test/screenshot/spec/mdc-data-table/classes/baseline-full-width.html
  test/screenshot/spec/mdc-data-table/classes/baseline-with-buttons.html
  test/screenshot/spec/mdc-data-table/classes/baseline.html
  test/screenshot/spec/mdc-data-table/fixture.js
  test/screenshot/spec/mdc-data-table/fixture.scss
  test/screenshot/spec/mdc-data-table/mixins/density.html
  test/screenshot/spec/mdc-data-table/mixins/fill-color.html
Labels: cla: yes

#5434 test(menusurface): Add Jasmine component test.
  packages/mdc-menu-surface/test/component.test.ts
  test/unit/mdc-menu-surface/mdc-menu-surface.test.js
Labels: cla: yes

#5431 test(floating-label): Add Jasmine foundation tests
  karma.conf.js
  packages/mdc-floating-label/test/foundation.test.ts
  test/unit/mdc-floating-label/mdc-floating-label-foundation.test.js
  testing/helpers/foundation.ts
Labels: cla: yes

#5435 test(notched-outline): Add Jasmine component unit tests
  packages/mdc-notched-outline/test/component.test.ts
  test/unit/mdc-notched-outline/mdc-notched-outline.test.js
Labels: cla: yes

#5437 test(floating-label): Add Jasmine component unit test
  packages/mdc-floating-label/test/component.test.ts
  test/unit/mdc-floating-label/mdc-floating-label.test.js
Labels: cla: yes

#5436 test(line-ripple): Add Jasmine component unit tests
  packages/mdc-line-ripple/test/component.test.ts
  test/unit/mdc-line-ripple/mdc-line-ripple.test.js
Labels: cla: yes

#5442 test(list): Remove list screenshot tests.
  test/screenshot/golden.json
  test/screenshot/spec/mdc-list/classes/baseline.html
  test/screenshot/spec/mdc-list/classes/checkbox.html
  test/screenshot/spec/mdc-list/classes/disabled-checkbox.html
  test/screenshot/spec/mdc-list/classes/disabled-items.html
  test/screenshot/spec/mdc-list/classes/disabled-radio.html
  test/screenshot/spec/mdc-list/classes/list-group.html
  test/screenshot/spec/mdc-list/classes/meta-text.html
  test/screenshot/spec/mdc-list/classes/radio.html
  test/screenshot/spec/mdc-list/classes/selected.html
  test/screenshot/spec/mdc-list/classes/two-line.html
  test/screenshot/spec/mdc-list/fixture.js
  test/screenshot/spec/mdc-list/fixture.scss
  test/screenshot/spec/mdc-list/mixins/density-checkbox.html
  test/screenshot/spec/mdc-list/mixins/density.html
  test/screenshot/spec/mdc-list/mixins/shape-single-line.html
Labels: cla: yes

#5444 docs(dialog): escape pipe characters
  packages/mdc-dialog/README.md
Labels: cla: yes

#5438 test(switch): Add Jasmine switch foundation test
  karma.conf.js
  packages/mdc-switch/test/foundation.test.ts
  test/unit/mdc-switch/foundation.test.js
Labels: cla: yes

#5445 chore: Stylelint rules to keep it in sync with internal
  .stylelintrc.yaml
  packages/mdc-checkbox/_variables.scss
  packages/mdc-drawer/_mixins.scss
  packages/mdc-grid-list/_mixins.scss
  packages/mdc-icon-button/_mixins.scss
  packages/mdc-layout-grid/_mixins.scss
  packages/mdc-select/_mixins.scss
  packages/mdc-slider/_mixins.scss
  packages/mdc-textfield/_mixins.scss
  packages/mdc-textfield/_variables.scss
  test/screenshot/spec/fixture.scss
Labels: cla: yes

#5449 fix(notched-outline): Restore component test
  packages/mdc-notched-outline/test/component.test.ts
Labels: cla: yes

#5408 refactor: avoid BEM naming for mixins
  packages/mdc-button/_mixins.scss
  packages/mdc-checkbox/_mixins.scss
  packages/mdc-fab/_mixins.scss
  packages/mdc-switch/_mixins.scss
  packages/mdc-tab-scroller/_mixins.scss
  packages/mdc-tab/_mixins.scss
Labels: cla: yes

#5450 test(icon-button): Add Jasmine foundation unit tests
  karma.conf.js
  packages/mdc-icon-button/test/foundation.test.ts
  test/unit/mdc-icon-button/foundation.test.js
Labels: cla: yes

#5451 test(menu): Remove menu screenshots.
  test/screenshot/golden.json
  test/screenshot/spec/mdc-menu/classes/baseline.html
  test/screenshot/spec/mdc-menu/classes/bottom-anchored.html
  test/screenshot/spec/mdc-menu/classes/menu-selection-group-only.html
  test/screenshot/spec/mdc-menu/classes/menu-selection-group.html
  test/screenshot/spec/mdc-menu/classes/multiple-menu-selection-group.html
  test/screenshot/spec/mdc-menu/fixture.js
  test/screenshot/spec/mdc-menu/fixture.scss
  test/screenshot/spec/mdc-menu/issues/4025.html
  test/screenshot/spec/mdc-menu/issues/fixture.scss
Labels: cla: yes

#5448 fix(floatinglabel): Estimate hidden scroll width
  packages/mdc-dom/README.md
  packages/mdc-dom/ponyfill.ts
  packages/mdc-floating-label/component.ts
  packages/mdc-floating-label/package.json
  packages/mdc-textfield/test/component.test.ts
  test/unit/mdc-dom/ponyfill.test.js
Labels: cla: yes

#5447 chore: Move tests from Travis to GitHub Actions
  .github/workflows/test.yml
  .travis.yml
  karma.conf.js
  package-lock.json
  package.json
  scripts/travis-env-vars.sh
Labels: cla: yes

#5454 test(topappbar): Add Jasmine foundation tests.
  karma.conf.js
  packages/mdc-top-app-bar/fixed/test/foundation.test.ts
  packages/mdc-top-app-bar/short/test/foundation.test.ts
  packages/mdc-top-app-bar/standard/test/foundation.test.ts
  packages/mdc-top-app-bar/test/foundation.test.ts
  test/unit/mdc-top-app-bar/fixed.foundation.test.js
  test/unit/mdc-top-app-bar/foundation.test.js
  test/unit/mdc-top-app-bar/short.foundation.test.js
  test/unit/mdc-top-app-bar/standard.foundation.test.js
  testing/helpers/foundation.ts
  testing/helpers/setup.ts
Labels: cla: yes

#5455 test(icon-button): Remove screenshot tests
  test/screenshot/golden.json
  test/screenshot/spec/mdc-icon-button/classes/baseline-icon-button-toggle.html
  test/screenshot/spec/mdc-icon-button/classes/baseline.html
  test/screenshot/spec/mdc-icon-button/fixture.js
  test/screenshot/spec/mdc-icon-button/fixture.scss
  test/screenshot/spec/mdc-icon-button/mixins/density.html
  test/screenshot/spec/mdc-icon-button/mixins/icon-size.html
  test/screenshot/spec/mdc-icon-button/mixins/ink-color.html
Labels: cla: yes

#5457 test(form-field): Add Jasmine component test
  karma.conf.js
  packages/mdc-form-field/test/foundation.test.ts
  test/unit/mdc-form-field/foundation.test.js
Labels: cla: yes

#5459 test(topappbar): Add Jasmine component test.
  packages/mdc-top-app-bar/test/component.test.ts
  test/unit/mdc-top-app-bar/mdc-top-app-bar.test.js
  testing/dom/events.ts
Labels: cla: yes

#5462 test(form-field): Add Jasmine component unit tests
  packages/mdc-form-field/test/component.test.ts
  test/unit/mdc-form-field/mdc-form-field.test.js
Labels: cla: yes

#5465 test(shape): Fix shape variable override usage after module migration
  test/screenshot/golden.json
  test/screenshot/spec/mdc-shape/fixture.scss
Labels: cla: yes

#5466 test(topappbar): Remove screenshots and demo code.
  test/screenshot/golden.json
  test/screenshot/spec/mdc-top-app-bar/classes/baseline-dense-prominent-with-action-items.html
  test/screenshot/spec/mdc-top-app-bar/classes/baseline-dense-prominent.html
  test/screenshot/spec/mdc-top-app-bar/classes/baseline-dense-with-action-items.html
  test/screenshot/spec/mdc-top-app-bar/classes/baseline-dense.html
  test/screenshot/spec/mdc-top-app-bar/classes/baseline-fixed-with-action-items.html
  test/screenshot/spec/mdc-top-app-bar/classes/baseline-fixed.html
  test/screenshot/spec/mdc-top-app-bar/classes/baseline-prominent-with-action-items.html
  test/screenshot/spec/mdc-top-app-bar/classes/baseline-prominent.html
  test/screenshot/spec/mdc-top-app-bar/classes/baseline-short-collapsed-with-action-items.html
  test/screenshot/spec/mdc-top-app-bar/classes/baseline-short-collapsed.html
  test/screenshot/spec/mdc-top-app-bar/classes/baseline-short-with-action-items.html
  test/screenshot/spec/mdc-top-app-bar/classes/baseline-short.html
  test/screenshot/spec/mdc-top-app-bar/classes/baseline-with-action-items.html
  test/screenshot/spec/mdc-top-app-bar/classes/baseline.html
  test/screenshot/spec/mdc-top-app-bar/fixture.js
  test/screenshot/spec/mdc-top-app-bar/fixture.scss
Labels: cla: yes

#5456 test(icon-button): Add Jasmine component unit tests
  packages/mdc-icon-button/test/component.test.ts
  test/unit/mdc-icon-button/mdc-icon-button-toggle.test.js
Labels: cla: yes

#5458 fix(textfield): prevent placeholder styles from collapsing with minifiers
  packages/mdc-floating-label/component.ts
  packages/mdc-textfield/_mixins.scss
  packages/mdc-textfield/component.ts
Labels: cla: yes

#5464 fix(auto-init): Fixed issue with multiple default exports
  packages/mdc-auto-init/index.ts
Labels: cla: yes

#5461 test: Ensure package.json dependencies match with actual dependencies
  .github/workflows/test.yml
  package.json
  packages/mdc-data-table/package.json
  packages/mdc-dialog/package.json
  packages/mdc-icon-button/package.json
  packages/mdc-menu/package.json
  packages/mdc-shape/package.json
  packages/mdc-snackbar/package.json
  packages/mdc-switch/package.json
  packages/mdc-tab-bar/package.json
  packages/mdc-top-app-bar/package.json
  packages/mdc-touch-target/package.json
  scripts/check-pkg-for-release.js
  scripts/dependency-test.sh
Labels: cla: yes

#5471 test(base): Add Jasmine component unit tests
  packages/mdc-base/test/component.test.ts
  test/unit/mdc-base/component.test.js
Labels: cla: yes

#5472 test(slider): Add Jasmine foundation tests.
  karma.conf.js
  packages/mdc-slider/adapter.ts
  packages/mdc-slider/component.ts
  packages/mdc-slider/foundation.ts
  packages/mdc-slider/test/foundation-general-events.test.ts
  packages/mdc-slider/test/foundation-keyboard-events.test.ts
  packages/mdc-slider/test/foundation-pointer-events.test.ts
  packages/mdc-slider/test/foundation.test.ts
  packages/mdc-slider/test/helpers.ts
  test/unit/mdc-slider/foundation-general-events.test.js
  test/unit/mdc-slider/foundation-keyboard-events.test.js
  test/unit/mdc-slider/foundation-pointer-events.test.js
  test/unit/mdc-slider/foundation.test.js
  testing/helpers/foundation.ts
Labels: cla: yes

#5473 test(animation): Add Jasmine component unit tests
  karma.conf.js
  packages/mdc-animation/test/component.test.ts
  test/unit/mdc-animation/mdc-animation.test.js
Labels: cla: yes

#5470 test(feature-targeting): Migrate feature targeting tests to jasmine
  .github/workflows/test.yml
  .gitignore
  jasmine-node.json
  karma.conf.js
  package.json
  packages/mdc-button/test/feature-targeting-all.test.scss
  packages/mdc-button/test/feature-targeting-any.test.scss
  packages/mdc-button/test/mdc-button.scss.test.ts
  test/scss/_feature-targeting-test.scss
  testing/helpers/sass-test-compile.helper.ts
  testing/helpers/ts-node.helper.js
  tsconfig-node.json
Labels: cla: yes

#5479 chore: Updated package-lock.json file after npm i
  package-lock.json
Labels: cla: yes

#5478 test(card): Remove screenshot tests
  test/screenshot/golden.json
  test/screenshot/spec/mdc-card/classes/baseline.html
  test/screenshot/spec/mdc-card/classes/media.html
  test/screenshot/spec/mdc-card/fixture.js
  test/screenshot/spec/mdc-card/fixture.scss
  test/screenshot/spec/mdc-card/mixins/color-and-shape.html
  test/screenshot/spec/mdc-card/mixins/media-aspect-ratio.html
Labels: cla: yes

#5477 fix(snackbar): adjust mixins to meet spec
  packages/mdc-snackbar/_mixins.scss
  test/screenshot/golden.json
Labels: cla: yes

#5132 fix(slider): use secondary custom property color for slider container
  packages/mdc-slider/_mixins.scss
Labels: Ready for Google, cla: yes

#5482 chore: update slider mixins indentation
  packages/mdc-slider/_mixins.scss
Labels: cla: yes

#5480 test(slider): Remove slider screenshot tests.
  test/screenshot/golden.json
  test/screenshot/spec/mdc-slider/classes/baseline_continuous.html
  test/screenshot/spec/mdc-slider/classes/baseline_discrete.html
  test/screenshot/spec/mdc-slider/fixture.js
  test/screenshot/spec/mdc-slider/fixture.scss
Labels: cla: yes

#5475 test(slider): Add Jasmine component test.
  packages/mdc-slider/test/component.test.ts
  test/unit/mdc-slider/helpers.js
  test/unit/mdc-slider/mdc-slider.test.js
Labels: cla: yes

#5481 test(snackbar): Add Jasmine foundation tests
  karma.conf.js
  packages/mdc-snackbar/test/foundation.test.ts
  test/unit/mdc-snackbar/foundation.test.js
Labels: cla: yes

#5487 chore: Import indentation changes
  karma.conf.js
  packages/mdc-auto-init/test/mdc-auto-init.test.ts
  packages/mdc-button/test/mdc-button.scss.test.ts
  testing/featuretargeting/index.ts
Labels: cla: yes

#5489 docs(layout-grid): fix incorrect variable name
  packages/mdc-layout-grid/README.md
Labels: cla: yes

#5490 test(snackbar): Add Jasmine component and util tests
  packages/mdc-snackbar/test/component.test.ts
  packages/mdc-snackbar/test/util.test.ts
  test/unit/mdc-snackbar/mdc-snackbar.test.js
  test/unit/mdc-snackbar/util.test.js
Labels: cla: yes

#5378 feat(text-field): add feature targeting for styles
  packages/mdc-textfield/_mixins.scss
  packages/mdc-textfield/character-counter/_mixins.scss
  packages/mdc-textfield/character-counter/mdc-text-field-character-counter.scss
  packages/mdc-textfield/helper-text/_mixins.scss
  packages/mdc-textfield/helper-text/mdc-text-field-helper-text.scss
  packages/mdc-textfield/icon/_mixins.scss
  packages/mdc-textfield/icon/mdc-text-field-icon.scss
  packages/mdc-textfield/mdc-text-field.scss
  packages/mdc-textfield/package.json
  test/scss/_feature-targeting-test.scss
Labels: cla: yes

#5497 fix(snackbar): add explicit width for label to wrap in ie11
  packages/mdc-snackbar/_mixins.scss
Labels: cla: yes

#5495 test(ripple): Add Jasmine foundation and util tests
  karma.conf.js
  packages/mdc-ripple/test/foundation-activation.test.ts
  packages/mdc-ripple/test/foundation-deactivation.test.ts
  packages/mdc-ripple/test/foundation-general-events.test.ts
  packages/mdc-ripple/test/foundation.test.ts
  packages/mdc-ripple/test/helpers.ts
  packages/mdc-ripple/test/util.test.ts
  test/unit/mdc-ripple/foundation-activation.test.js
  test/unit/mdc-ripple/foundation-deactivation.test.js
  test/unit/mdc-ripple/foundation-general-events.test.js
  test/unit/mdc-ripple/foundation.test.js
  test/unit/mdc-ripple/helpers.js
  test/unit/mdc-ripple/util.test.js
Labels: cla: yes

#5498 test(ripple): Add Jasmine component tests
  packages/mdc-ripple/test/component.test.ts
  test/unit/mdc-ripple/mdc-ripple.test.js
Labels: cla: yes

#5499 refactor(grid-list): Remove grid-list component
  packages/material-components-web/index.ts
  packages/material-components-web/material-components-web.scss
  packages/material-components-web/package.json
  packages/mdc-grid-list/.npmignore
  packages/mdc-grid-list/README.md
  packages/mdc-grid-list/_mixins.import.scss
  packages/mdc-grid-list/_mixins.scss
  packages/mdc-grid-list/_variables.import.scss
  packages/mdc-grid-list/_variables.scss
  packages/mdc-grid-list/adapter.ts
  packages/mdc-grid-list/component.ts
  packages/mdc-grid-list/constants.ts
  packages/mdc-grid-list/foundation.ts
  packages/mdc-grid-list/index.ts
  packages/mdc-grid-list/mdc-grid-list.import.scss
  packages/mdc-grid-list/mdc-grid-list.scss
  packages/mdc-grid-list/package-lock.json
  packages/mdc-grid-list/package.json
  scripts/webpack/css-bundle-factory.js
  scripts/webpack/js-bundle-factory.js
  test/scss/_feature-targeting-test.scss
  test/unit/mdc-grid-list/foundation.test.js
  test/unit/mdc-grid-list/mdc-grid-list.test.js
Labels: cla: yes

#5492 fix(slider): Fix for slider on an absolute positioned parent element
  packages/mdc-slider/foundation.ts
  packages/mdc-slider/test/foundation-general-events.test.ts
  packages/mdc-slider/test/foundation-pointer-events.test.ts
Labels: Ready for Google, cla: yes

#5504 test(linear-progress): Remove screenshot tests
  test/screenshot/golden.json
  test/screenshot/spec/mdc-linear-progress/classes/baseline.html
  test/screenshot/spec/mdc-linear-progress/fixture.js
  test/screenshot/spec/mdc-linear-progress/fixture.scss
  test/screenshot/spec/mdc-linear-progress/mixins/bar-color.html
  test/screenshot/spec/mdc-linear-progress/mixins/buffer-color.html
Labels: cla: yes

#5506 test: Removed feature targeting test files that tests with all…
  packages/mdc-button/test/feature-targeting-all.test.scss
  packages/mdc-card/test/feature-targeting-all.test.scss
  packages/mdc-checkbox/test/feature-targeting-all.test.scss
  packages/mdc-chips/test/feature-targeting-all.test.scss
  packages/mdc-data-table/test/feature-targeting-all.test.scss
  packages/mdc-dialog/test/feature-targeting-all.test.scss
  packages/mdc-drawer/test/feature-targeting-all.test.scss
  packages/mdc-elevation/test/feature-targeting-all.test.scss
  packages/mdc-fab/test/feature-targeting-all.test.scss
  packages/mdc-floating-label/test/feature-targeting-all.test.scss
  packages/mdc-form-field/test/feature-targeting-all.test.scss
  packages/mdc-icon-button/test/feature-targeting-all.test.scss
  packages/mdc-line-ripple/test/feature-targeting-all.test.scss
  packages/mdc-linear-progress/test/feature-targeting-all.test.scss
  packages/mdc-list/test/feature-targeting-all.test.scss
  packages/mdc-menu-surface/test/feature-targeting-all.test.scss
  packages/mdc-menu/test/feature-targeting-all.test.scss
  packages/mdc-notched-outline/test/feature-targeting-all.test.scss
  packages/mdc-radio/test/feature-targeting-all.test.scss
  packages/mdc-ripple/test/feature-targeting-all.test.scss
  packages/mdc-shape/test/feature-targeting-all.test.scss
  packages/mdc-slider/test/feature-targeting-all.test.scss
  packages/mdc-snackbar/test/feature-targeting-all.test.scss
  packages/mdc-switch/test/feature-targeting-all.test.scss
  packages/mdc-tab-bar/test/feature-targeting-all.test.scss
  packages/mdc-tab-indicator/test/feature-targeting-all.test.scss
  packages/mdc-tab-scroller/test/feature-targeting-all.test.scss
  packages/mdc-tab/test/feature-targeting-all.test.scss
  packages/mdc-textfield/test/feature-targeting-all.test.scss
  packages/mdc-theme/test/feature-targeting-all.test.scss
  packages/mdc-touch-target/test/feature-targeting-all.test.scss
  packages/mdc-typography/test/feature-targeting-all.test.scss
Labels: cla: yes

#5507 test(linear-progress): Add Jasmine foundation tests
  karma.conf.js
  packages/mdc-linear-progress/test/foundation.test.ts
  packages/mdc-ripple/test/foundation-activation.test.ts
  packages/mdc-ripple/test/foundation-deactivation.test.ts
  packages/mdc-ripple/test/foundation-general-events.test.ts
  packages/mdc-ripple/test/helpers.ts
  test/unit/mdc-linear-progress/foundation.test.js
  testing/helpers/foundation.ts
Labels: cla: yes

#5439 fix(textfield): change root element to <label>
  README.md
  docs/migrating-from-mdl.md
  packages/mdc-auto-init/README.md
  packages/mdc-floating-label/README.md
  packages/mdc-notched-outline/README.md
  packages/mdc-select/README.md
  packages/mdc-textfield/README.md
  packages/mdc-textfield/helper-text/README.md
  packages/mdc-textfield/icon/README.md
  packages/mdc-textfield/icon/foundation.ts
  packages/mdc-textfield/test/component.test.ts
  test/screenshot/spec/mdc-rtl/variables/include.html
  test/screenshot/spec/mdc-shape/variables/override.html
Labels: cla: yes

#5503 test(snackbar): Remove screenshot tests for snackbar component
  test/screenshot/golden.json
  test/screenshot/spec/mdc-snackbar/classes/baseline-with-action.html
  test/screenshot/spec/mdc-snackbar/classes/baseline-without-action.html
  test/screenshot/spec/mdc-snackbar/classes/leading.html
  test/screenshot/spec/mdc-snackbar/classes/stacked.html
  test/screenshot/spec/mdc-snackbar/fixture.js
  test/screenshot/spec/mdc-snackbar/fixture.scss
  test/screenshot/spec/mdc-snackbar/mixins/elevation.html
  test/screenshot/spec/mdc-snackbar/mixins/fill-color.html
  test/screenshot/spec/mdc-snackbar/mixins/label-ink-color.html
  test/screenshot/spec/mdc-snackbar/mixins/max-width.html
  test/screenshot/spec/mdc-snackbar/mixins/min-width.html
  test/screenshot/spec/mdc-snackbar/mixins/shape-radius.html
  test/screenshot/spec/mdc-snackbar/mixins/viewport-margin.html
Labels: cla: yes

#5508 test(linear-progress): Add Jasmine component unit tests
  packages/mdc-linear-progress/test/component.test.ts
  test/unit/mdc-linear-progress/mdc-linear-progress.test.js
Labels: cla: yes

#5505 feat(dom): Add focus trap utility.
  karma.conf.js
  packages/mdc-dialog/component.ts
  packages/mdc-dialog/package.json
  packages/mdc-dialog/util.ts
  packages/mdc-dom/README.md
  packages/mdc-dom/focus-trap.ts
  packages/mdc-dom/index.ts
  packages/mdc-dom/test/focus-trap.test.ts
  packages/mdc-drawer/component.ts
  packages/mdc-drawer/package.json
  packages/mdc-drawer/util.ts
  scripts/lint-mdc.ts
  test/unit/mdc-dialog/mdc-dialog.test.js
  test/unit/mdc-dialog/util.test.js
  test/unit/mdc-drawer/mdc-drawer.test.js
  test/unit/mdc-drawer/util.test.js
Labels: cla: yes

#5513 chore: Log a message when tests run on forked repo
  .github/workflows/test.yml
Labels: cla: yes

#5512 fix(slider): slider track not visible
  packages/mdc-slider/_mixins.scss
Labels: Ready for Google, cla: yes

#5511 fix(switch): fix strict generic checks
  packages/mdc-switch/component.ts
Labels: cla: yes

#4978 fix(slider): Visual bug when slider value is displayed as "-0"
  packages/mdc-slider/foundation.ts
  packages/mdc-slider/test/foundation-pointer-events.test.ts
Labels: Ready for Google, cla: yes

#5518 test(dialog): Add Jasmine foundation/util tests.
  karma.conf.js
  packages/mdc-dialog/test/foundation.test.ts
  packages/mdc-dialog/test/util.test.ts
  test/unit/mdc-dialog/foundation.test.js
  test/unit/mdc-dialog/util.test.js
Labels: cla: yes

#5519 test(dialog): Add Jasmine component test.
  packages/mdc-dialog/test/component.test.ts
  test/unit/mdc-dialog/mdc-dialog.test.js
  testing/dom/events.ts
Labels: cla: yes

#5510 docs(icon-button): remove stray aria-hidden
  packages/mdc-icon-button/README.md
Labels: cla: yes

#5523 Fix data table docs.
  packages/mdc-data-table/README.md
Labels: cla: yes

#5496 fix(textfield): outlined trailing icon's position
  packages/mdc-textfield/_mixins.scss
Labels: cla: yes

#5524 test: Helper to get foundation methods, including superclasses
  testing/helpers/foundation.ts
Labels: cla: yes

#5525 test(switch): migrate MDC Switch component unit tests to Jasmine
  packages/mdc-switch/test/component.test.ts
  test/unit/mdc-switch/mdc-switch.test.js
Labels: cla: yes

#5522 test(tab-indicator): Migrate tab indicator unit tests to Jasmine
  karma.conf.js
  packages/mdc-tab-indicator/test/component.test.ts
  packages/mdc-tab-indicator/test/fading-foundation.test.ts
  packages/mdc-tab-indicator/test/sliding-foundation.test.ts
  test/unit/mdc-tab-indicator/foundation.test.js
  test/unit/mdc-tab-indicator/mdc-tab-indicator.test.js
  test/unit/mdc-tab-indicator/sliding-foundation.test.js
Labels: cla: yes

#5488 docs(card): update action buttons to v4
  packages/mdc-card/README.md
  packages/mdc-dialog/README.md
  packages/mdc-snackbar/README.md
Labels: cla: yes

#5527 feat(dom): Create announcer utility
  packages/mdc-dom/README.md
  packages/mdc-dom/announce.ts
  packages/mdc-dom/test/announce.test.ts
Labels: cla: yes

#5526 test(switch): Remove switch screenshot tests
  test/screenshot/golden.json
  test/screenshot/spec/mdc-switch/classes/baseline.html
  test/screenshot/spec/mdc-switch/fixture.js
  test/screenshot/spec/mdc-switch/fixture.scss
  test/screenshot/spec/mdc-switch/mixins/density.html
  test/screenshot/spec/mdc-switch/mixins/thumb-color.html
  test/screenshot/spec/mdc-switch/mixins/track-color.html
Labels: cla: yes

#5493 fix(data-table): change svg attribute name viewbox to viewBox (#5483)
  packages/mdc-data-table/README.md
  packages/mdc-data-table/test/component.test.ts
Labels: Ready for Google, cla: yes

#5534 chore: Add nvmrc
  .nvmrc
Labels: cla: yes

#5536 test(drawer): Migrate drawer unit tests to Jasmine
  karma.conf.js
  packages/mdc-drawer/dismissible/test/foundation.test.ts
  packages/mdc-drawer/modal/test/foundation.test.ts
  packages/mdc-drawer/test/component.test.ts
  packages/mdc-drawer/test/util.test.ts
  test/unit/mdc-drawer/dismissible.foundation.test.js
  test/unit/mdc-drawer/mdc-drawer.test.js
  test/unit/mdc-drawer/modal.foundation.test.js
  testing/dom/index.ts
Labels: cla: yes

#5538 chore: Add copybara comment lines for transformation
  packages/mdc-select/mdc-select.scss
  packages/mdc-textfield/mdc-text-field.scss
Labels: cla: yes

#5530 test(dom): Migrate MDC Dom unit tests to use Jasmine
  packages/mdc-dom/README.md
  packages/mdc-dom/events.ts
  packages/mdc-dom/test/events.test.ts
  packages/mdc-dom/test/ponyfill.test.ts
  test/unit/mdc-dom/ponyfill.test.js
Labels: cla: yes

#5533 chore: Remove any custom lint rules
  package.json
  scripts/lint-mdc.ts
Labels: cla: yes

#5537 fix(chips): Fix browser back nav in FF when removing chip with backspace key.
  packages/mdc-chips/chip/foundation.ts
  packages/mdc-chips/chip/test/foundation.test.ts
Labels: cla: yes

#5546 feat: Add index stylesheets to mdc-image-list and mdc-layout-grid.
  packages/mdc-image-list/_index.scss
  packages/mdc-image-list/_mixins.import.scss
  packages/mdc-image-list/_variables.import.scss
  packages/mdc-layout-grid/_index.scss
  packages/mdc-layout-grid/_mixins.import.scss
  packages/mdc-layout-grid/_variables.import.scss
  test/screenshot/spec/mdc-image-list/fixture.scss
Labels: cla: yes

#5460 feat(line-ripple): add active/inactive states to line-ripple
  packages/mdc-line-ripple/_mixins.scss
  packages/mdc-line-ripple/test/feature-targeting-any.test.scss
  packages/mdc-select/_mixins.scss
  packages/mdc-textfield/_mixins.scss
Labels: cla: yes

#5543 chore: Remove MDC fab screenshot test files
  test/screenshot/golden.json
  test/screenshot/spec/mdc-fab/classes/baseline.html
  test/screenshot/spec/mdc-fab/classes/extended.html
  test/screenshot/spec/mdc-fab/classes/mini.html
  test/screenshot/spec/mdc-fab/fixture.js
  test/screenshot/spec/mdc-fab/fixture.scss
  test/screenshot/spec/mdc-fab/mixins/extended-padding.html
  test/screenshot/spec/mdc-fab/mixins/extended-shape-radius.html
  test/screenshot/spec/mdc-fab/mixins/shape-radius.html
Labels: cla: yes

#5545 chore: Remove MDC form field screenshot test files
  test/screenshot/golden.json
  test/screenshot/spec/mdc-form-field/classes/baseline-radio-rtl.html
  test/screenshot/spec/mdc-form-field/classes/baseline-radio.html
  test/screenshot/spec/mdc-form-field/fixture.js
Labels: cla: yes

#5550 feat(chips): Announce when chips are removed
  packages/mdc-chips/README.md
  packages/mdc-chips/chip-set/adapter.ts
  packages/mdc-chips/chip-set/component.ts
  packages/mdc-chips/chip-set/foundation.ts
  packages/mdc-chips/chip-set/test/component.test.ts
  packages/mdc-chips/chip-set/test/foundation.test.ts
  packages/mdc-chips/chip/adapter.ts
  packages/mdc-chips/chip/component.ts
  packages/mdc-chips/chip/constants.ts
  packages/mdc-chips/chip/foundation.ts
  packages/mdc-chips/chip/test/foundation.test.ts
  packages/mdc-chips/chip/types.ts
  packages/mdc-chips/package.json
Labels: cla: yes
